# 服务端口
server:
  port: 9712
# 服务名
spring:
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.0.101:3306/guli_edu?characterEncoding=utf-8&useSSL=false
    username: root
    password: sa
  application:
    name: guli_teacher
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:org/phoneix/Teacher/mapper/xml/*Mapper.xml